version: "3.7"
services:
  ups-compute-and-network:
    build:
      context: "apcupsd-image"
    image: crossan007/apcupsd
    ports:
      - "3551:3551"
    devices:
      - "/dev/usb/ups-compute-and-network:/dev/ups"
    environment:
      - UPSNAME=ComputeAndNetwork
  ups-screen:
    build:
      context: "apcupsd-image"
    image: crossan007/apcupsd
    ports:
     - "3552:3551"
    devices:
     -  "/dev/usb/ups-screen:/dev/ups"
    environment:
      - UPSNAME=Screens
  http-ups-status:
    build:
      context: "multimon-image"
    image: crossan007/apcupsd-multimon
    ports:
      - "82:80"
    environment:
      - "UPS_TO_MONITOR=ups-screen,ups-compute-and-network"
